;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Cooldowns.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Ranged.ConeShot",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Ranged.PointBlankShot",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Ranged.SniperShot",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Special.Rewind",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Thrown.Grenade.Time",DevComment="")
+GameplayTagList=(Tag="Cooldowns.Thrown.Grenade.Volatile",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Movement.Dash.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Ranged.ConeShot",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Ranged.ConeShot.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Ranged.PointBlankShot",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Ranged.PointBlankShot.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Ranged.SniperShot",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Ranged.SniperShot.AnimNotify",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Ranged.SniperShot.CompleteNotify",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Ranged.SniperShot.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Special.Rewind",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Special.Rewind.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Thrown.Grenade",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Thrown.Grenade.ThrowCompleteNotify",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Thrown.Grenade.ThrowNotify",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Thrown.Grenade.Time.Cooldown",DevComment="")
+GameplayTagList=(Tag="GameplayAbilities.Thrown.Grenade.Volatile.Cooldown",DevComment="")

